services:
  userservice:
    build:
      context: .
      dockerfile: UserService/InnoShop.UserService.WebApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__App=Server=database;Database=UserDb;User Id=sa;Password=${DATABASE_PASSWORD};TrustServerCertificate=True
    user: appuser
    depends_on:
      - database
    networks:
      - innoshop-network

  productservice:
    build:
      context: .
      dockerfile: ProductService/InnoShop.ProductService.WebApi/Dockerfile
    ports:
      - "8082:8080"
      - "8083:8081"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__App=Server=database;Database=ProductDb;User Id=sa;Password=${DATABASE_PASSWORD};TrustServerCertificate=True
    user: appuser
    depends_on:
      - database
    networks:
      - innoshop-network

  gatewayservice:
    build:
      context: .
      dockerfile: GatewayService/InnoShop.GatewayService.WebApi/Dockerfile
    ports:
      - "8084:8080"
      - "8085:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    user: appuser
    networks:
      - innoshop-network

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DATABASE_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - innoshop-network

networks:
  innoshop-network:
    driver: bridge

volumes:
  sqldata:
    driver: local